"""
TC3 Compliance Checker
Sends a pay equity narrative report to local Ollama.
Model evaluates compliance with EU Directive 2023/970 and returns structured checklist JSON.

Usage:
    python tc3_checker.py                        # runs all built-in test cases
    python tc3_checker.py "your report text"     # single custom report
"""

import json
import sys
import urllib.request
import urllib.error

# ── SETTINGS ─────────────────────────────────────────────────────────────────

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "phi3.5:latest"   # change to: llama3.1:8b | mistral:7b

SYSTEM_PROMPT = """You are a pay equity compliance auditor specializing in EU Directive 2023/970. You will receive a pay equity analysis report written in natural language. Your task is to evaluate whether the report meets the reporting requirements of the Directive and return a structured JSON compliance assessment.

Directive 2023/970 reporting requirements (Art. 9):
1. mean_gap_reported: The report must state the mean pay gap between comparison groups
2. median_gap_reported: The report must state the median pay gap between comparison groups
3. quartile_distribution_reported: The report must describe the distribution of pay across quartiles (Q1, Q2, Q3) by group
4. controlled_gap_reported: The report must include a gap estimate that controls for relevant variables (e.g. experience, education)
5. joint_assessment_triggered: If mean or median gap exceeds 5%, the report must explicitly state that a joint pay assessment is required
6. scope_defined: The report must clearly define which employee groups were compared and any filters applied

Return only valid JSON in this exact format:
{
  "compliant": <true if all checklist items are true, false otherwise>,
  "checklist": {
    "mean_gap_reported": <true|false>,
    "median_gap_reported": <true|false>,
    "quartile_distribution_reported": <true|false>,
    "controlled_gap_reported": <true|false>,
    "joint_assessment_triggered": <true|false>,
    "scope_defined": <true|false>
  },
  "violations": [<list of strings describing missing or incorrect elements, empty list if compliant>]
}

Return only valid JSON. No explanation."""

# ── TEST CASES ────────────────────────────────────────────────────────────────

# Reports generated by TC2 narrator (Mistral output — best quality)
REPORT_COMPLIANT = """
This pay equity analysis was conducted under EU Directive 2023/970, focusing on the comparison of income between male and female employees within job levels 3 and 4. The analysis controlled for education level and experience years.

Key findings demonstrate a mean gender gap of 5.5% (absolute difference: PLN 464.47), with women earning on average PLN 7977.10 compared to men's PLN 8441.57. The median gender gap was 4.87%, amounting to PLN 328.00, with women earning a median income of PLN 6401.00 and men earning PLN 6729.00.

The quartile distribution shows the following: women's income ranged from Q1 of PLN 4488.00 to Q3 of PLN 8306.00, with a maximum of PLN 36840.00 for 105 female employees. For men, Q1 was PLN 4447.00, Q3 was PLN 8921.50, and the maximum was PLN 40105.00 for 127 male employees.

The controlled gap analysis, accounting for education level and years of experience, revealed a residual absolute gap of PLN 540.96, indicating that the raw gap cannot be fully explained by these control variables.

The analysis confirms non-compliance with Directive 2023/970: the mean gender pay gap of 5.5% exceeds the 5% threshold. A joint pay assessment is required under Article 9 of the directive.
"""

REPORT_MISSING_QUARTILES = """
This analysis compares income between male and female employees at senior and lead job levels under EU Directive 2023/970.

The mean gender pay gap is 5.5%, with women earning PLN 7977.10 on average versus PLN 8441.57 for men. The median gap is 4.87%.

After controlling for education level and experience years, the adjusted gap remains at PLN 540.96, confirming a persistent pay disparity.

The mean gap exceeds the 5% threshold under Directive 2023/970. A joint pay assessment is required per Article 9.
"""

REPORT_MISSING_CONTROLLED_AND_JOINT = """
A pay equity analysis was conducted comparing income between male and female employees at job levels 3 and 4.

The mean income for women is PLN 7977.10 versus PLN 8441.57 for men, representing a gap of 5.5%. The median income for women is PLN 6401.00 compared to PLN 6729.00 for men, a gap of 4.87%.

The income distribution by quartile shows: women Q1=PLN 4488, Q3=PLN 8306; men Q1=PLN 4447, Q3=PLN 8921.

No further action has been identified at this time.
"""

TEST_CASES = [
    {
        "id": "TC3-01",
        "description": "Fully compliant report",
        "report": REPORT_COMPLIANT,
        "expected": {
            "compliant": True,
            "checklist": {
                "mean_gap_reported": True,
                "median_gap_reported": True,
                "quartile_distribution_reported": True,
                "controlled_gap_reported": True,
                "joint_assessment_triggered": True,
                "scope_defined": True
            },
            "violations": []
        }
    },
    {
        "id": "TC3-02",
        "description": "Missing quartile distribution",
        "report": REPORT_MISSING_QUARTILES,
        "expected": {
            "compliant": False,
            "checklist": {
                "mean_gap_reported": True,
                "median_gap_reported": True,
                "quartile_distribution_reported": False,
                "controlled_gap_reported": True,
                "joint_assessment_triggered": True,
                "scope_defined": True
            },
            "violations": ["Quartile distribution not reported"]
        }
    },
    {
        "id": "TC3-03",
        "description": "Missing controlled gap and joint assessment trigger",
        "report": REPORT_MISSING_CONTROLLED_AND_JOINT,
        "expected": {
            "compliant": False,
            "checklist": {
                "mean_gap_reported": True,
                "median_gap_reported": True,
                "quartile_distribution_reported": True,
                "controlled_gap_reported": False,
                "joint_assessment_triggered": False,
                "scope_defined": True
            },
            "violations": [
                "Controlled gap not reported",
                "Joint pay assessment not triggered despite gap exceeding 5%"
            ]
        }
    }
]

# ── VALIDATION & SCORING ──────────────────────────────────────────────────────

CHECKLIST_KEYS = [
    "mean_gap_reported",
    "median_gap_reported",
    "quartile_distribution_reported",
    "controlled_gap_reported",
    "joint_assessment_triggered",
    "scope_defined"
]

def validate_output(output: dict) -> list:
    errors = []
    if "compliant" not in output:
        errors.append("Missing field: 'compliant'")
    if "checklist" not in output:
        errors.append("Missing field: 'checklist'")
    else:
        for key in CHECKLIST_KEYS:
            if key not in output["checklist"]:
                errors.append(f"Missing checklist key: '{key}'")
    if "violations" not in output:
        errors.append("Missing field: 'violations'")
    return errors

def score_against_expected(actual: dict, expected: dict) -> dict:
    scores = {}

    scores["compliant"] = actual.get("compliant") == expected.get("compliant")

    checklist_actual = actual.get("checklist", {})
    checklist_expected = expected.get("checklist", {})
    checklist_correct = sum(
        checklist_actual.get(k) == checklist_expected.get(k)
        for k in CHECKLIST_KEYS
    )
    scores["checklist"] = f"{checklist_correct}/{len(CHECKLIST_KEYS)}"

    violations_actual = set(actual.get("violations", []))
    violations_expected = set(expected.get("violations", []))
    # Soft match: check count matches rather than exact strings
    scores["violations_count_match"] = len(violations_actual) == len(violations_expected)

    correct_fields = sum([
        scores["compliant"],
        checklist_correct == len(CHECKLIST_KEYS),
        scores["violations_count_match"]
    ])
    scores["total"] = f"{correct_fields}/3"
    return scores

# ── OLLAMA CALL ───────────────────────────────────────────────────────────────

def call_ollama(report_text: str) -> str:
    prompt = (
        "Evaluate this pay equity report for compliance with EU Directive 2023/970:\n\n"
        + report_text.strip()
    )

    payload = json.dumps({
        "model": MODEL,
        "system": SYSTEM_PROMPT,
        "prompt": prompt,
        "stream": False
    }).encode("utf-8")

    req = urllib.request.Request(
        OLLAMA_URL,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST"
    )

    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            return data.get("response", "").strip()
    except urllib.error.URLError as e:
        return f"ERROR: {e}"

# ── PARSE JSON ────────────────────────────────────────────────────────────────

def parse_json_response(raw: str) -> tuple:
    raw = raw.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    try:
        return json.loads(raw), None
    except json.JSONDecodeError as e:
        return None, str(e)

# ── MAIN ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if len(sys.argv) > 1:
        test_cases = [{"id": "CUSTOM", "description": "Custom report", "report": " ".join(sys.argv[1:]), "expected": None}]
    else:
        test_cases = TEST_CASES

    results_summary = []

    for tc in test_cases:
        print(f"\n{'='*60}")
        print(f"TEST CASE: {tc['id']} — {tc['description']}")
        print(f"{'='*60}")

        raw_response = call_ollama(tc["report"])
        print(f"\nRAW MODEL OUTPUT:\n{raw_response}")

        output, parse_error = parse_json_response(raw_response)

        if parse_error:
            print(f"\n[FAIL] JSON parse error: {parse_error}")
            results_summary.append({"id": tc["id"], "status": "PARSE_FAIL", "score": "0/3"})
            continue

        print(f"\nPARSED OUTPUT:\n{json.dumps(output, indent=2)}")

        errors = validate_output(output)
        if errors:
            print(f"\n[VALIDATION ERRORS]")
            for e in errors:
                print(f"  - {e}")
        else:
            print(f"\n[VALIDATION] OK")

        if tc.get("expected"):
            scores = score_against_expected(output, tc["expected"])
            print(f"\n[SCORE vs EXPECTED]")
            print(f"  compliant field:         {'OK' if scores['compliant'] else 'FAIL'}")
            print(f"  checklist accuracy:      {scores['checklist']}")
            print(f"  violations count match:  {'OK' if scores['violations_count_match'] else 'FAIL'}")
            print(f"  TOTAL: {scores['total']}")
            results_summary.append({
                "id": tc["id"],
                "status": "OK" if not errors else "INVALID",
                "score": scores["total"]
            })

    print(f"\n{'='*60}")
    print(f"SUMMARY — MODEL: {MODEL}")
    print(f"{'='*60}")
    for r in results_summary:
        print(f"  {r['id']}: {r['status']} | score {r['score']}")
